In [72]:
import pandas as pd

In [73]:
df = pd.read_csv("Indian Unicorn startups 2023 updated.csv")

In [74]:
print(df)

     No.             Company                                  Sector  \
0      1              InMobi                     Adtech - Mobile Ads
1      2           Flipkart^                              E-Commerce
2      3            Mu Sigma                        SaaS - Analytics
3      4           Snapdeal*                              E-Commerce
4      5              PayTM^             Fintech - Payments & Wallet
..   ...                 ...                                     ...
97    98             Purplle  E-Commerce - Personal Care & Cosmetics
98    99         Leadsquared                              SaaS - CRM
99   100             OneCard                  Fintech - Credit Cards
100  101          Shiprocket         Aggregator - Logistics Services
101  102  Molbio Diagnostics                Healthtech - Diagnostics

     Entry Valuation^^ ($B)  Valuation ($B)     Entry             Location  \
0                      1.00            1.00  Sep/2011  Bangalore/Singapore
1                      1.00           37.60  Feb/2012  Bangalore/Singapore
2                      1.00            1.50  Feb/2013    Bangalore/Chicago
3                      1.80            2.40  Oct/2014                Delhi
4                      1.70           16.00  Feb/2015                Noida
..                      ...             ...       ...                  ...
97                     1.10            1.10  Jun/2022               Mumbai
98                     1.00            1.00  Jun/2022            Bangalore
99                     1.30            1.30  Jul/2022                 Pune
100                    1.23            1.23  Aug/2022                Delhi
101                    1.53            1.53  Sep/2022                  Goa

                                      Select Investors
0                    KPCB, Sherpalo Ventures, SoftBank
1      Accel, Tiger Global, Naspers, SoftBank, Tencent
2             Accel, Sequoia Capital, General Atlantic
3    Kalaari Capital, Nexus Ventures, Bessemer, Sof...
4    Saama Capital, Elevation Capital, Alibaba, Ber...
..                                                 ...
97   JSW Ventures, IvyCap Ventures, Blume Ventures,...
98         Stakeboat Capital, Gaja Capital, WestBridge
99   QED Investors, Matrix Partners India, Sequoia ...
100  Lightrock India, Info Edge, Tribe Capital, Tem...
101                             Temasek, Motilal Oswal

[102 rows x 8 columns]

In [75]:
df["Company"] = (
    df["Company"]
    .str.replace("^", "", regex=False)
    .str.replace("*", "", regex=False)
    .str.strip()
)

print(df.head(15))

    No.       Company                       Sector  Entry Valuation^^ ($B)  \
0     1        InMobi          Adtech - Mobile Ads                     1.0
1     2      Flipkart                   E-Commerce                     1.0
2     3      Mu Sigma             SaaS - Analytics                     1.0
3     4      Snapdeal                   E-Commerce                     1.8
4     5         PayTM  Fintech - Payments & Wallet                     1.7
5     6      Ola Cabs   Mobility - Ride Aggregator                     1.6
6     7         Quikr    Marketplace - Classifieds                     1.0
7     8        Zomato                     Foodtech                     1.0
8     9     ShopClues                   E-Commerce                     1.1
9    10          Hike     Social Media - Messaging                     1.4
10   11         BYJUS                       Edtech                     1.0
11   12    PayTM Mall                   E-Commerce                     1.9
12   13        Swiggy                     Foodtech                     1.4
13   14  PolicyBazaar          Fintech - Insurance                     1.0
14   15    Freshworks                   SaaS - CRM                     1.5

    Valuation ($B)     Entry             Location  \
0              1.0  Sep/2011  Bangalore/Singapore
1             37.6  Feb/2012  Bangalore/Singapore
2              1.5  Feb/2013    Bangalore/Chicago
3              2.4  Oct/2014                Delhi
4             16.0  Feb/2015                Noida
5              7.3  Mar/2015            Bangalore
6              1.5  Apr/2015            Bangalore
7              5.4  Sep/2015              Gurgaon
8              1.1  Jan/2016              Gurgaon
9              1.4  Aug/2016                Delhi
10            22.0  Jan/2018            Bangalore
11             3.0  Apr/2018                Noida
12            10.7  Jun/2018            Bangalore
13             2.4  Jun/2018              Gurgaon
14             3.5  Jul/2018    Chennai/San Mateo

                                     Select Investors
0                   KPCB, Sherpalo Ventures, SoftBank
1     Accel, Tiger Global, Naspers, SoftBank, Tencent
2            Accel, Sequoia Capital, General Atlantic
3   Kalaari Capital, Nexus Ventures, Bessemer, Sof...
4   Saama Capital, Elevation Capital, Alibaba, Ber...
5   Tiger Global, Matrix Partners, Steadview, Soft...
6   Matrix Partners, Omidyar Network, Norwest, Kin...
7   Info Edge, Sequoia Capital, Vy Capital, Alibab...
8   Nexus Ventures, Helion Ventures, Beenos, Tiger...
9                      Tiger Global, Tencent, Foxconn
10  Aarin Capital, Sequoia Capital, Lightspeed Ven...
11         Elevation Capital, Alibaba, SoftBank, eBay
12  Accel, Elevation Capital, Norwest, Naspers, Te...
13  Info Edge, Intel, Inventus Capital, Tiger Glob...
14  Accel, Tiger Global, Google, Sequoia Capital, ...

In [76]:
df.head()

,No.,Company,Sector,Entry Valuation^^ ($B),Valuation ($B),Entry,Location,Select Investors
0,1,InMobi,Adtech - Mobile Ads,1.0,1.0,Sep/2011,Bangalore/Singapore,"KPCB, Sherpalo Ventures, SoftBank"
1,2,Flipkart,E-Commerce,1.0,37.6,Feb/2012,Bangalore/Singapore,"Accel, Tiger Global, Naspers, SoftBank, Tencent"
2,3,Mu Sigma,SaaS - Analytics,1.0,1.5,Feb/2013,Bangalore/Chicago,"Accel, Sequoia Capital, General Atlantic"
3,4,Snapdeal,E-Commerce,1.8,2.4,Oct/2014,Delhi,"Kalaari Capital, Nexus Ventures, Bessemer, Sof..."
4,5,PayTM,Fintech - Payments & Wallet,1.7,16.0,Feb/2015,Noida,"Saama Capital, Elevation Capital, Alibaba, Ber..."

In [77]:
df.columns

Index(['No.', 'Company', 'Sector', 'Entry Valuation^^ ($B)', 'Valuation ($B)',
       'Entry', 'Location', 'Select Investors'],
      dtype='object')

In [78]:
df = df[["Company", "Sector", "Location"]]
df.head()

    Company                       Sector             Location
0    InMobi          Adtech - Mobile Ads  Bangalore/Singapore
1  Flipkart                   E-Commerce  Bangalore/Singapore
2  Mu Sigma             SaaS - Analytics    Bangalore/Chicago
3  Snapdeal                   E-Commerce                Delhi
4     PayTM  Fintech - Payments & Wallet                Noida

In [79]:
df["Website"] = (
    "https://www."
    + df["Company"]
    .str.lower()
    .str.replace(" ", "", regex=False)
    .str.replace("^", "", regex=False)
    .str.replace("*", "", regex=False)
    + ".com"
)

print(df.head())

    Company                       Sector             Location  \
0    InMobi          Adtech - Mobile Ads  Bangalore/Singapore
1  Flipkart                   E-Commerce  Bangalore/Singapore
2  Mu Sigma             SaaS - Analytics    Bangalore/Chicago
3  Snapdeal                   E-Commerce                Delhi
4     PayTM  Fintech - Payments & Wallet                Noida

                    Website
0    https://www.inmobi.com
1  https://www.flipkart.com
2   https://www.musigma.com
3  https://www.snapdeal.com
4     https://www.paytm.com

In [80]:
df.drop_duplicates(inplace=True)

print(df.shape)

(102, 4)

In [81]:
df["Generated Email"] = (
    df["Company"]
    .str.lower()
    .str.replace(" ", "", regex=False)
    .str.replace("^", "", regex=False)
    .str.replace("*", "", regex=False)
    + "@gmail.com"
)

print(df.head())

    Company                       Sector             Location  \
0    InMobi          Adtech - Mobile Ads  Bangalore/Singapore
1  Flipkart                   E-Commerce  Bangalore/Singapore
2  Mu Sigma             SaaS - Analytics    Bangalore/Chicago
3  Snapdeal                   E-Commerce                Delhi
4     PayTM  Fintech - Payments & Wallet                Noida

                    Website     Generated Email
0    https://www.inmobi.com    inmobi@gmail.com
1  https://www.flipkart.com  flipkart@gmail.com
2   https://www.musigma.com   musigma@gmail.com
3  https://www.snapdeal.com  snapdeal@gmail.com
4     https://www.paytm.com     paytm@gmail.com

In [82]:
df["LinkedIn"] = (
    "https://www.linkedin.com/search/results/all/?keywords="
    + df["Company"]
    .str.replace(" ", "%20")
)

print(df.head())

    Company                       Sector             Location  \
0    InMobi          Adtech - Mobile Ads  Bangalore/Singapore
1  Flipkart                   E-Commerce  Bangalore/Singapore
2  Mu Sigma             SaaS - Analytics    Bangalore/Chicago
3  Snapdeal                   E-Commerce                Delhi
4     PayTM  Fintech - Payments & Wallet                Noida

                    Website     Generated Email  \
0    https://www.inmobi.com    inmobi@gmail.com
1  https://www.flipkart.com  flipkart@gmail.com
2   https://www.musigma.com   musigma@gmail.com
3  https://www.snapdeal.com  snapdeal@gmail.com
4     https://www.paytm.com     paytm@gmail.com

                                            LinkedIn
0  https://www.linkedin.com/search/results/all/?k...
1  https://www.linkedin.com/search/results/all/?k...
2  https://www.linkedin.com/search/results/all/?k...
3  https://www.linkedin.com/search/results/all/?k...
4  https://www.linkedin.com/search/results/all/?k...

In [83]:
df.fillna("Not Available", inplace=True)

print(df.isnull().sum())

Company            0
Sector             0
Location           0
Website            0
Generated Email    0
LinkedIn           0
dtype: int64

In [84]:
url = "https://quotes.toscrape.com/"

response = requests.get(url)

soup = BeautifulSoup(response.text, "html.parser")

quotes = soup.find_all("span", class_="text")

scraped_quotes = []

for quote in quotes:
    scraped_quotes.append(quote.text)

print(scraped_quotes[:5])

['“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”', '“It is our choices, Harry, that show what we truly are, far more than our abilities.”', '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”', '“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”', "“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”"]

In [85]:
df.to_excel("final_leads.xlsx", index=False)

print("Excel file created successfully!")

print("Total Leads:", len(df))

Excel file created successfully!
Total Leads: 102

In [86]:
df.to_excel("final_leads.xlsx", index=False)

print("Excel file created successfully!")

Excel file created successfully!

In [87]:
!pip install schedule

Requirement already satisfied: schedule in /usr/local/lib/python3.12/dist-packages (1.2.2)

In [88]:
import schedule
import time

def automate_task():
    print("Lead generation task executed successfully!")

schedule.every(10).seconds.do(automate_task)

print("Automation started...")

schedule.run_pending()
time.sleep(10)

Automation started...
Lead generation task executed successfully!
Lead generation task executed successfully!